// <auto-generated />
using System;
using HwEmployees.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HwEmployees.Migrations
{
    [DbContext(typeof(EmpDbContext))]
    [Migration("20220129132707_emp-table")]
    partial class emptable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HwEmployees.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DOB = new DateTime(2002, 1, 29, 15, 27, 6, 880, DateTimeKind.Local).AddTicks(6461),
                            Name = "ali",
                            Salary = 1000
                        },
                        new
                        {
                            Id = 2,
                            DOB = new DateTime(2002, 1, 29, 15, 27, 6, 886, DateTimeKind.Local).AddTicks(3566),
                            Name = "ahmad",
                            Salary = 2000
                        },
                        new
                        {
                            Id = 3,
                            DOB = new DateTime(2002, 1, 29, 15, 27, 6, 886, DateTimeKind.Local).AddTicks(3661),
                            Name = "nada",
                            Salary = 3000
                        },
                        new
                        {
                            Id = 4,
                            DOB = new DateTime(2002, 1, 29, 15, 27, 6, 886, DateTimeKind.Local).AddTicks(3676),
                            Name = "heba",
                            Salary = 1500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
